#!/bin/bash
set -e

# Function to download Paper Minecraft server
download_paper() {
    local version=$1
    
    # If version is "latest", get the latest build number
    if [ "$version" = "latest" ]; then
        echo "Finding latest Paper version..."
        # Get the latest Minecraft version
        MC_VERSION=$(curl -s https://papermc.io/api/v2/projects/paper | jq -r '.versions[-1]')
        echo "Latest Minecraft version: $MC_VERSION"
        
        # Get the latest build for this version
        BUILD=$(curl -s "https://papermc.io/api/v2/projects/paper/versions/${MC_VERSION}" | jq -r '.builds[-1]')
        echo "Latest build: $BUILD"
    else
        # Use the specified version
        MC_VERSION=$version
        # Get the latest build for this version
        BUILD=$(curl -s "https://papermc.io/api/v2/projects/paper/versions/${MC_VERSION}" | jq -r '.builds[-1]')
        echo "Latest build for $MC_VERSION: $BUILD"
    fi
    
    # Download the server jar
    echo "Downloading Paper server jar..."
    curl -s "https://papermc.io/api/v2/projects/paper/versions/${MC_VERSION}/builds/${BUILD}/downloads/paper-${MC_VERSION}-${BUILD}.jar" -o /data/paper.jar
    echo "Downloaded paper-${MC_VERSION}-${BUILD}.jar"
}

# Check if EULA is accepted
if [ "$EULA" != "true" ]; then
    echo "You need to accept the Minecraft EULA by setting the EULA environment variable to 'true'."
    exit 1
fi

# Create server directory structure if it doesn't exist
mkdir -p /data/world
mkdir -p /data/plugins
mkdir -p /data/logs

# Create eula.txt if it doesn't exist
if [ ! -f /data/eula.txt ]; then
    echo "eula=true" > /data/eula.txt
    echo "Created eula.txt"
fi

# Download server jar if it doesn't exist
if [ ! -f /data/paper.jar ]; then
    download_paper "$MINECRAFT_VERSION"
fi

# Create server.properties if it doesn't exist
if [ ! -f /data/server.properties ]; then
    cat > /data/server.properties << EOL
#Minecraft server properties
#Generated by Docker
enable-jmx-monitoring=false
rcon.port=25575
level-seed=
gamemode=survival
enable-command-block=false
enable-query=false
generator-settings={}
level-name=world
motd=Minecraft Server powered by AWS
query.port=25565
pvp=true
generate-structures=true
difficulty=normal
network-compression-threshold=256
max-tick-time=60000
require-resource-pack=false
max-players=20
use-native-transport=true
online-mode=true
enable-status=true
allow-flight=false
broadcast-rcon-to-ops=true
view-distance=10
server-ip=
resource-pack-prompt=
allow-nether=true
server-port=25565
enable-rcon=false
sync-chunk-writes=true
op-permission-level=4
prevent-proxy-connections=false
resource-pack=
entity-broadcast-range-percentage=100
rcon.password=
player-idle-timeout=0
force-gamemode=false
rate-limit=0
hardcore=false
white-list=false
broadcast-console-to-ops=true
spawn-npcs=true
spawn-animals=true
snooper-enabled=true
function-permission-level=2
level-type=default
text-filtering-config=
spawn-monsters=true
enforce-whitelist=false
resource-pack-sha1=
spawn-protection=16
max-world-size=29999984
EOL
    echo "Created server.properties"
fi

# Start the server
echo "Starting Minecraft server..."
exec java -Xms"$MEMORY" -Xmx"$MEMORY" -jar /data/paper.jar nogui
